Update the layout for the main feature and add the logout floating bu…
Glints-007/Attendance-Mobile pull request #3
Opened 2021-09-17 17:40 UTC by chaterinamf

Did you write good & comprehensive specs? ⭐️
no

What's this PR do ? ⭐️
update the layout that matches to raendy's design and add the logout floating button

What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Create-layout-for-clock-in-clock-out-feature-in-mobile-773c3ee55062440987f44137822aa49d

Where should the reviewer start ?

How should this be manually tested ?

What is the Dockup URL ?

Any background context you want to provide ?

Any deployment note (migrations, new envs, rake tasks, cron) ?

Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/81873379/133830787-0e5ce22a-9793-4a64-a3f4-c65425448aa1.png)

Definition of Done:

[x] Specs / Tests are adequate ? ⭐️

[x] Changes conform with code quality tools (Rubocop, Reek, Brakeman) ? ⭐️

[x] Does this PR require Database changes ?

[x] Does this PR require monitoring after deployment (Scout, logs, Sentry, etc) ?

[x] Does this PR require a regression test by QA ? All fixes require a regression test.

[x] Does this add new dependencies ? (network setup, new 3rd party services)

2021-09-17 17:42 UTC, andranugraha approved these changes

2021-09-18 18:00 UTC, rahmatullah5 requested changes
Please make sure all the image assets is already optimized, you can use lossless image compression such as https://kraken.io/

2021-09-18 18:24 UTC, rahmatullah5 reviewed
Please remove any comment if you will not use the code anymore

2021-09-18 18:24 UTC, rahmatullah5 commented on app/src/main/java/com/example/attendance/ui/MainActivity.kt
> +        val currentTime = SimpleDateFormat("hh:mm a", Locale.getDefault()).format(Date())
Why do we need to store the value first? can we just return it right `away?`

```
fun getCurrentTime(): String {
return SimpleDateFormat("hh:mm a", Locale.getDefault()).format(Date())
```

2021-09-19 05:39 UTC, chaterinamf commented on app/src/main/java/com/example/attendance/ui/MainActivity.kt
> +        val currentTime = SimpleDateFormat("hh:mm a", Locale.getDefault()).format(Date())
yes, it can. I store the value first just to make a clean appearance

2021-09-20 08:24 UTC, rahmatullah5 approved these changes

2021-09-20 08:25 UTC, rahmatullah5 approved these changes

2021-09-20 09:38 UTC, merged