Finishing touch
Glints-007/Attendance-Mobile pull request #9
Opened 2021-10-05 16:08 UTC by chaterinamf

Did you write good & comprehensive specs? ⭐️
no

What's this PR do ? ⭐️
Makesure there is no main feature are left behind for this project

What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Finishing-touch-mobile-4acbfc629d8e476cb6e7b5a417783c90

Screenshots (if appropriate)

Definition of Done:

[y] Specs / Tests are adequate ? ⭐️

[x] Changes conform with code quality tools (Rubocop, Reek, Brakeman) ? ⭐️

[x] Does this PR require Database changes ?

[x] Does this PR require monitoring after deployment (Scout, logs, Sentry, etc) ?

[y] Does this PR require a regression test by QA ? All fixes require a regression test.

[x] Does this add new dependencies ? (network setup, new 3rd party services)

2021-10-06 03:16 UTC, rahmatullah5 requested changes

2021-10-06 03:16 UTC, rahmatullah5 commented on app/src/main/java/com/example/attendance/model/ClockHistoryResponse.kt
> +    val userId: String? = null
Why did we use string instead of int fo userId ?

2021-10-06 03:16 UTC, rahmatullah5 commented on app/src/main/java/com/example/attendance/model/ClockHistoryResponse.kt
> +    val updatedAt: String? = null
Why did we use string instead of date for this updatedAt ?

2021-10-06 03:16 UTC, rahmatullah5 commented on app/src/main/java/com/example/attendance/ui/MainActivity.kt
> +            Log.d("Coordinate", "Lat : $lat \nLong : $long")
Remove the log from the code.

2021-10-06 03:21 UTC, chaterinamf commented on app/src/main/java/com/example/attendance/model/ClockHistoryResponse.kt
> +    val updatedAt: String? = null
the response of userId is in string, for instance: "user_id": "c85fead6-420e-4676-86ae-bdaacaa7f522"

2021-10-06 04:31 UTC, chaterinamf commented on app/src/main/java/com/example/attendance/ui/MainActivity.kt
> +            Log.d("Coordinate", "Lat : $lat \nLong : $long")
fixed

2021-10-07 04:42 UTC, herulhidayat approved these changes

2021-10-07 06:54 UTC, rahmatullah5 approved these changes

2021-10-07 06:57 UTC, merged